### ISSUE TITLE
instructions.css Bug Report

### ISSUE THREAD

**Issue by skibop** [skibop/Voyageur#13]
The code you provided is a CSS (Cascading Style Sheets) file, which contains styling rules for a webpage. I couldn't find any syntax errors or bugs that would prevent the code from functioning as intended. However, I can suggest a few improvements and best practices:

1. It is a good idea to include a CSS reset or normalize stylesheet at the beginning of your CSS file to ensure consistent rendering across different browsers. You can use a popular reset/normalize library or create your own.

2. Instead of using hardcoded values for paddings, margins, and other dimensions, consider using CSS variables or custom properties. This will make it easier to maintain and update your stylesheet.

3. Group related selectors together to improve readability and maintainability.

4. Use more specific selectors when necessary to avoid unintended side effects.

5. Consider adding comments to describe the purpose and functionality of different sections of your CSS file.

6. Use a linter or a style guide to enforce consistent coding practices and catch potential issues early on.

Here's an example of how you could apply some of these suggestions to your code:

```css
/* Custom Properties */
:root {
  --padding: 20px;
  --margin: 10px;
  --border-radius: 5px;
  --box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.3);
}

/* Body Styles */
body {
  font-family: 'Open Sans', sans-serif;
  margin: 0;
  padding: 0;
  background: linear-gradient(to right, #4285f4, #b388ff);
  color: #fff;
  overflow: hidden;
}

/* Header Styles */
header {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: var(--padding);
  backdrop-filter: blur(10px);
}

/* Heading Styles */
h1 {
  margin: 0;
  color: #fff;
  text-align: center;
  font-size: 2em;
}

/* Navigation Styles */
.navbar {
  display: flex;
  justify-content: center;
  list-style: none;
  padding: 0;
}

.nav-link {
  text-decoration: none;
  color: #fff;
  padding: var(--padding);
  margin: 0 var(--margin);
  border-radius: var(--border-radius);
  transition: background-color 0.3s ease;
}

.nav-link:hover {
  background-color: rgba(255, 255, 255, 0.2);
}

/* Main Styles */
main {
  max-width: 800px;
  margin: var(--margin) auto;
  padding: var(--padding);
}

/* Section Styles */
section {
  margin-bottom: var(--margin);
  padding: var(--padding);
  border-radius: var(--border-radius);
  backdrop-filter: blur(10px);
  transition: transform 0.3s ease, box-shadow 0.3s ease, background-color 0.3s ease;
}

/* Glass Effect Styles */
.glass {
  background: rgba(0, 0, 0, 0.2);
  box-shadow: var(--box-shadow);
}

.glass:hover {
  transform: translateY(-5px);
  box-shadow: 0 16px 40px 0 rgba(0, 0, 0, 0.5);
  background: rgba(0, 0, 0, 0.3);
}

/* Footer Styles */
footer {
  text-align: center;
  padding: var(--padding);
}

/* Logo Styles */
.logo {
  max-width: 400px;
  max-height: 400px;
  width: auto;
  height: auto;
  position: absolute;
  top: -110px;
  left: -90px;
}

/* Instruction List Styles */
.instruction-list {
  font-size: 1.2em;
  list-style-type: none;
}

.instruction-list li {
  font-size: 1.1em;
  margin-bottom: 20px;
  position: relative;
}

.instruction-list li:before {
  content: "\2022";
  color: #fff;
  font-weight: bold;
  display: inline-block;
  width: 1em;
  position: absolute;
  left: -1.5em;
  top: 0.1em;
}
```
