### ISSUE TITLE
index.css Bug Report

### ISSUE THREAD

**Issue by skibop** [skibop/Voyageur#27]
There are no major bugs in the provided code, but there are a few potential improvements that could be made:

1. The `backdrop-filter` property may not be supported in some older browsers. You can add vendor prefixes to increase compatibility:

```css
header {
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
  -moz-backdrop-filter: blur(10px);
  -ms-backdrop-filter: blur(10px);
}

.section {
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
  -moz-backdrop-filter: blur(10px);
  -ms-backdrop-filter: blur(10px);
}

.modal {
  backdrop-filter: blur(5px);
  -webkit-backdrop-filter: blur(5px);
  -moz-backdrop-filter: blur(5px);
  -ms-backdrop-filter: blur(5px);
}
```

2. The `flex: 1` property is used in the `.profile-content` and `.text-content` selectors, but it is not necessary since there is only one flex item in each container. You can remove these declarations.

3. The `.logo` selector is defined twice, which is unnecessary. You can remove the second definition.

4. The `.text-content h1` selector is used to add margin to `h1` elements inside `.text-content`. However, this rule may affect other `h1` elements in the document if they are not inside a `.text-content` container. To avoid this, you can use a more specific selector like `.profile-content .text-content h1`.

Here's the improved code:

```css
/* Body Styles */
body {
  font-family: 'Open Sans', sans-serif; /* Set font family */
  margin: 0; /* Remove default margin */
  padding: 0; /* Remove default padding */
  background: linear-gradient(to right, #4285f4, #b388ff); /* Blue to Light Purple gradient background */
  color: #fff; /* Set text color to white */
  overflow: hidden; /* Add this line to remove the scrollbar */
}

/* Header Styles */
header {
  display: flex; /* Set display to flex */
  flex-direction: column; /* Set flex direction to column */
  justify-content: center; /* Center align content vertically */
  align-items: center; /* Center align content horizontally */
  padding: 40px 20px; /* Padding */
  backdrop-filter: blur(10px); /* Apply blur effect */
  -webkit-backdrop-filter: blur(10px);
  -moz-backdrop-filter: blur(10px);
  -ms-backdrop-filter: blur(10px);
  position: relative;
}

/* Logo Styles - Placed within the header selector */
.logo {
  max-width: 400px; /* Set maximum width */
  max-height: 400px; /* Set maximum height */
  width: auto; /* Maintain aspect ratio */
  height: auto; /* Maintain aspect ratio */
  position: absolute; /* Set position to absolute */
  top: -110px; /* Position from top */
  left: -90px; /* Position from left */
}

/* Heading Styles */
h1 {
  margin: 0; /* Remove default margin */
  color: #fff; /* Set text color to white */
  text-align: center; /* Center align text */
}

/* Navigation Styles */
.navbar {
  display: flex; /* Set display to flex */
  justify-content: center; /* Center align navigation links horizontally */
  list-style: none; /* Remove default list style */
  padding: 0; /* Remove default padding */
}

.nav-link {
  text-decoration: none; /* Remove underline from links */
  color: #fff; /* Set text color to white */
  padding: 10px 20px; /* Padding */
  margin: 0 10px; /* Margin */
  border-radius: 5px; /* Add border radius */
  transition: background-color 0.3s ease; /* Smooth transition for background color */
}

.nav-link:hover {
  background-color: rgba(255, 255, 255, 0.2); /* Lighten background color on hover */
}

/* Main Styles */
main {
  max-width: 800px; /* Set maximum width */
  margin: 20px auto; /* Center align with auto margins */
  padding: 20px; /* Padding */
}

/* Section Styles */
section {
  margin-bottom: 20px; /* Add margin bottom */
  padding: 20px; /* Padding */
  border-radius: 10px; /* Add border radius */
  backdrop-filter: blur(10px); /* Apply blur effect */
  -webkit-backdrop-filter: blur(10px);
  -moz-backdrop-filter: blur(10px);
  -ms-backdrop-filter: blur(10px);
  transition: transform 0.3s ease, box-shadow 0.3s ease, background-color 0.3s ease; /* Smooth transitions */
}

/* Glass Effect Styles */
.glass {
  background: rgba(0, 0, 0, 0.2); /* Semi-transparent background */
  box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.3); /* Box shadow */
}

.glass:hover {
  transform: translateY(-5px); /* Move up on hover */
  box-shadow: 0 16px 40px 0 rgba(0, 0, 0, 0.5); /* Larger shadow on hover */
  background: rgba
